[package]
name = "colored_2d_mesh_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["render"]

[dev-dependencies]
bevy = "0.7.0"